sonar.projectKey=vikita91_pdffonts
sonar.organization=lob-qa

sonar.projectName=pdffonts
sonar.projectVersion=3.6.1

sonar.sources=src,lib
sonar.tests=test
sonar.test.inclusions=test/**/*.test.js,test/**/*.js
sonar.exclusions=test/**

sonar.cfamily.compile-commands=bw-output/compile_commands.json

sonar.coverageReportPaths=coverage-sonar.xml

sonar.sourceEncoding=UTF-8
